services:
  ekg:
    build: .
    stdin_open: true
    tty: true
    command: python app.py
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
